MicroPad/MicroPad-Core

src/js/client/css/notepadStyle.css, src/js/client/js/client.js
Also rounds the end of lines for fancyness
=> Fix drawing offset

app/src/theme-styles/IanPad.css
=> Reference to Bears

app/package.json, app/yarn.lock
=> Bump up the parser version

app/src/components/search/SearchComponent.tsx
See https://github.com/electron/electron/issues/360
=> Detect electron running on macOS for workaround

app/src/components/search/SearchComponent.tsx
=> Ignore hashtags for general search

app/src/actions.ts, app/src/components/header/NotepadDropdownComponent.tsx, app/src/containers/header/NotepadDropdownContainer.ts, app/src/epics/NotepadEpics.ts, app/src/reducers/BaseReducer.ts, app/src/reducers/IsExportingReducer.ts, app/src/types/ReducerType.ts, app/src/types/index.tsx
=> Adding a loading state to exports.

app/package.json, app/src/core/reducers/NotepadsReducer.ts, app/src/react-web/DifferenceEngine.ts, app/src/react-web/epics/SyncEpics.ts, app/yarn.lock
Most of these fixes actually come from the parser, but this contains the update to the new version of the parser.
=> Fix: Encryption sync issues

app/src/core/actions.ts, app/src/core/reducers/NoteReducer.ts, app/src/core/reducers/NotepadsReducer.ts, app/src/react-web/components/header/HeaderComponent.tsx, app/src/react-web/containers/header/HeaderContainer.ts, app/src/react-web/epics/StorageEpics.ts, app/src/react-web/index.css, app/src/react-web/index.tsx
=> MicroPad will now automatically open your last notepad on launch

app/src/react-web/epics/CryptoEpics.ts, app/src/react-web/epics/StorageEpics.ts, app/src/react-web/util.ts
=> Making sure notepads stay encrypted when updating their asset usage

README.md
=> Removed waffle from the README

README.md
Hi Nick,
I noticed that the links for the dependencies in the README.md were incorrectly formatted so I quickly fixed them up.
Cheers,
Finn
=> Fixed the dependency links in README.md

app/src/react-web/components/explorer/ExplorerOptionsComponent.tsx, app/src/react-web/components/sync/SyncOptionsComponent.tsx
=> #146 fix: updating wording

app/package.json, app/src/core/actions.ts, app/src/react-web/components/search/SearchComponent.tsx, app/src/react-web/containers/header/HeaderContainer.ts, app/src/react-web/dialogs.ts, app/src/react-web/epics/HelpEpics.ts, app/src/react-web/epics/NotepadEpics.ts, app/src/react-web/epics/index.ts, app/src/react-web/epics/tests/HelpEpics.spec.ts, app/src/react-web/index.tsx, app/src/react-web/shortcuts.ts, app/yarn.lock
=> Stop overwriting the help notebook if the user has already got it

app/package.json, app/src/core/actions.ts, app/src/react-web/components/header/ImportMarkdownComponent.tsx, app/src/react-web/components/header/NotepadDropdownComponent.tsx, app/src/react-web/containers/header/ImportMarkdownContainer.ts, app/src/react-web/epics/NotepadEpics.ts, app/yarn.lock
=> Markdown Import

app/package.json, app/src/core/epics/tests/ExplorerEpics.spec.ts, app/src/react-web/components/note-viewer/elements/drawing/DrawingElementComponent.tsx, app/src/react-web/epics/StorageEpics.ts, app/src/react-web/epics/tests/HelpEpics.spec.ts, app/yarn.lock
I'm not sure if this will actually fix #167, but I'll find out when this gets released.
=> A potential fix for #167 (blocking saves)

app/src/react-web/components/header/NotepadBreadcrumbsComponent/NotepadBreadcrumbsComponent.css
=> Fix for breadcrumb scrolling

app/src/react-web/components/note-viewer/elements/markdown/enable-tabs.js
=> Keep markdown tab level

app/src/react-web/components/explorer/ExplorerOptionsComponent.tsx
=> Graduated the encrypt button from experimental options to the real deal

app/src/react-web/components/note-viewer/elements/PdfElementComponent.tsx, app/src/react-web/epics/NoteEpics.ts
Fixed 3 bugs in one go! v1 import regression has been fixed, blobs will have their MIME type set to PDF if it's a PDF element fixing #188, and the initial upload PDF blank element bug has been fixed.
=> Fixing PDF related bugs

app/public/index.html
Doing it from the right branch this time, hopefully
=> Correct equation to use capital letters

app/src/app/actions.ts, app/src/app/components/HelpMessageComponent.tsx, app/src/app/components/explorer/DueDateListComponent.tsx, app/src/app/components/explorer/NotepadExplorerComponent.css, app/src/app/components/explorer/NotepadExplorerComponent.tsx, app/src/app/components/note-viewer/NoteViewerComponent.css, app/src/app/components/note-viewer/elements/markdown/MarkdownElementComponent.tsx, app/src/app/containers/DueDateListContainer.ts, app/src/app/epics/DueDatesEpics.ts, app/src/app/epics/index.ts, app/src/app/reducers/NotepadsReducer.ts, app/src/app/root.tsx, app/src/app/services/DueDates.ts, app/src/app/types/NotepadTypes.ts
=> Allow due dates to be viewed from all notebooks

app/src/app/components/note-viewer/elements/markdown/MarkdownElementComponent.tsx
=> Fix underscores in Latex

app/package.json, app/yarn.lock
I'm really really sorry about the PR spam, hopefully this will fix the licence issues 🤞
=> Update fend to v0.1.12

app/src/app/components/search/SearchComponent.tsx
=> Fix search with sections that have a trailing space at the end

app/package.json, app/yarn.lock
Reverts MicroPad/MicroPad-Core#289
=> Revert "Bump opus-recorder from 4.1.4 to 8.0.3 in /app"

app/package.json, app/yarn.lock
https://github.com/printfn/fend/releases/tag/v0.1.17
Sorry about the confusion, I didn't set up the branch correctly before.
=> Update fend to v0.1.17

app/package.json
See https://github.com/MicroPad/MicroPad-Electron/issues/48
=> Bump the version number for an electron bug fix

app/integration/src/unsupported-page.spec.ts, app/integration/src/utils/general-ui.ts, app/public/index.html, app/src/index.tsx
Removing the hack from the static index.html and bringing it into the app following the MDN docs for how to properly ask for storage perms.
=> Fix persistence request

app/src/app/ThemeValues.ts, app/src/app/types/Themes.ts
[Gruvbox](https://github.com/morhetz/gruvbox?tab=readme-ov-file) is a popular theme for Vim.
It is licensed under [MIT/X11](https://en.wikipedia.org/wiki/MIT_License)
=> Add gruvbox theme
